@startuml
left to right direction

abstract class TroposphericPropagator {
Field calculate()
}

class TroposphericPadePropagator {

}

TroposphericPropagator <|- TroposphericPadePropagator
TroposphericPropagator <|- TroposphericPETOOLPropagator
TroposphericPropagator <|- KnifeEdgeDiffractionPropagator



@enduml