@startuml
left to right direction

'TroposphericPadePropagator *--HelmholtzPadeSolver

class HelmholtzPadeSolver {
    propagate()
    oprimize_params()
}

class HelmholtzPropagatorComputationalParams {
'    max_range_m: float
'    max_height_m: float
'    dx_wl: float
'    dz_wl: float
'    max_propagation_angle: float
'    max_src_angle: float
'    exp_pade_order: tuple
'    x_output_filter: int
'    z_output_filter: int
'    two_way: bool
'    two_way_iter_num: int
'    two_way_threshold: float
'    standard_pe: bool
'    sqrt_alpha: float
'    z_order: int
'    terrain_method: TerrainMethod
'    tol: float
'    storage: HelmholtzPropagatorStorage
'    max_abc_permittivity: float
}

'enum TerrainMethod {
'
'}

'HelmholtzPropagatorComputationalParams *-- TerrainMethod

interface HelmholtzPropagatorStorage {
DiscreteNonLocalBC get_nlbc()
set_nlbc(DiscreteNonLocalBC)
}

'HelmholtzPropagatorStorage <|- PickleStorage

HelmholtzPadeSolver *-- HelmholtzPropagatorComputationalParams
HelmholtzPadeSolver *-- HelmholtzEnvironment
HelmholtzPadeSolver *-- HelmholtzPropagatorStorage
'HelmholtzPadeSolver o- DiscreteBC

'BoundaryCondition <|- RobinBC
'BoundaryCondition <|- TransparentBC

interface BoundaryCondition {

}

'class RobinBC {
'q_1
'q_2
'q_3
'}
'
'class TransparentBC {
'beta
'gamma
'}
'
'interface DiscreteBC {
'
'}
'
'class DiscreteLocalBC {
'
'}

'class DiscreteNonLocalBC {
'
'}

'DiscreteBC <|- DiscreteLocalBC
'DiscreteBC <|- DiscreteNonLocalBC

HelmholtzEnvironment o- BoundaryCondition

class HelmholtzEnvironment {
'    x_max_m: float
'    lower_bc: BoundaryCondition
'    upper_bc: BoundaryCondition
'    z_min: float
'    z_max: float
'    n2minus1: types.FunctionType
'    use_n2minus1: bool
'    rho: types.FunctionType
'    use_rho: bool = True
'    terrain: types.FunctionType
'    knife_edges: List[Edge]
}

'class Edge {
'    x: float
'    z_min: float
'    z_max: float
'}

'HelmholtzEnvironment o- Edge

@enduml